# Stage 1: Build
FROM rust:1.78 as builder

WORKDIR /usr/src/brute-http

COPY brute-http/Cargo.toml brute-http/Cargo.lock ./

RUN mkdir src && echo "fn main() {}" > src/main.rs

RUN cargo build --release
RUN rm -f target/release/deps/brute*

COPY brute-http/ ./
COPY migrations ./migrations

RUN cargo build

FROM rust:1.78

WORKDIR /usr/src/brute-http

RUN apt-get update && \
    apt-get install -y \
    libssl-dev libpq-dev pkg-config ca-certificates \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/brute-http /usr/src/brute-http

ENV DATABASE_URL=postgresql://postgres:{password}@{host}/{database}
ENV BEARER_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ENV IPINFO_TOKEN=xxxxxxxxxxxxxx
ENV RUST_LOG=trace
ENV RUST_LOG_STYLE=always
ENV RATE_LIMIT=5
ENV RATE_LIMIT_DURATION=1
ENV LISTEN_ADDRESS=0.0.0.0:3000
ENV RUNNING_IN_DOCKER=true

EXPOSE 3000

# todo run the actual binary...
CMD ["cargo", "run", "--release"]

